### PR TITLE
handle oob more careful

### LINKED ISSUE #83: ns_cmdline.c's replace_variable() does not handle out of memory case
### Description
- Type: Bug 

---------------------------------------------------------------
## Bug

**mbed-client-cli version**
v0.3.0-42-g169f7dc

**Expected Behavior**
Out of memory is handled gracefully.

**Actual Behavior**
Undefined behavior if memory allocation fails in replace_variable(), ie in https://github.com/ARMmbed/mbed-client-cli/blob/169f7dcc80a7243ae43d3e1600a3ba243d95b2b0/source/ns_cmdline.c#L1407 and https://github.com/ARMmbed/mbed-client-cli/blob/169f7dcc80a7243ae43d3e1600a3ba243d95b2b0/source/ns_cmdline.c#L1410

**Steps to Reproduce**

----------------------------------------------------------------
## Enhancement

**Reason to enhance/problem with existing solution**

**Suggested enhancement**
Check for OOM, replace pointless "MEM_ALLOC(6)" with a "char valueLocal[6]" or something. Shouldn't the max length of output buffer be also 11 for 32b ints, not 6?

**Pros**

**Cons**

-----------------------------------------------------------------

## Question

**How to?**

### PR DESCRIPTION
**Pull request by jupe**
## Status
**READY**

## Migrations
NO

## Description
Fixes #83

follow up changes needed to verify that styles are correct select one and no warnings allowed..

### CODE REVIEW

File: source/ns_cmdline.c [hunk 1]
```diff
@@ -1401,20 +1401,22 @@ static void replace_variable(char *str, cmd_variable_t* variable_ptr)
...
     int name_len = strlen(variable_ptr->name_ptr);
     char* value;
+    char valueLocal[11];
     if (variable_ptr->type == VALUE_TYPE_STR) {
       value = variable_ptr->value.ptr;
     } else {
-      value = MEM_ALLOC(6);
-      int written = snprintf(value, 6, "%d", variable_ptr->value.i);
+      value = valueLocal;
+      int written = snprintf(value, 11, "%d", variable_ptr->value.i);
```
Comment (TeroJaasko) [inline source/ns_cmdline.c]: This has invalid two char indentation and compiler warning for unused ```written``` variable

Comment (jupe) [reply source/ns_cmdline.c]: good catch. We have to improve CI to catch these more carefully..

Comment (jupe) [reply source/ns_cmdline.c]: fixed.
